name: Docker Deploy Jenkins

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/custom-jenkins-with-docker:latest .

    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/custom-jenkins-with-docker:latest

    - name: Run Jenkins container
      run: |
        docker stop jenkins-container || true
        docker rm jenkins-container || true
        docker run -d \
          --name jenkins-container \
          -p 8080:8080 \
          -p 50000:50000 \
          -v jenkins_home:/var/jenkins_home \
          -v /var/run/docker.sock:/var/run/docker.sock \
          ${{ secrets.DOCKER_USERNAME }}/custom-jenkins-with-docker:latest
